### ISSUE TITLE
import module failing

### ISSUE THREAD

**Issue by swfiua** [lzybkr/PSReadLine#137]
Just installed this with psget, but it is failing to import :(

Import-Module : The 'H:\WindowsPowerShell\Modules\PSReadLine\PSReadLine.psd1' module cannot be imported because its man
ifest contains one or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModule
s', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostN
ame', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 'Typ
esToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'F
unctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the members that are not valid ('
RootModule'), then try to import the module again.
At line:1 char:14
- Import-Module <<<<  PSReadLine
  - CategoryInfo          : InvalidData: (H:\WindowsPower...PSReadLine.psd1:String) [Import-Module], InvalidOperatio
    nException
  - FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by litmit** [comment]
Same troubles for me (Powershell 2.0). Please add requirements for Powershell version into readme.md.
