### ISSUE TITLE
PowerShell.OnIdle event handlers don't work with PSReadline

### ISSUE THREAD

**Issue by lzybkr** [lzybkr/PSReadLine#169]
PSReadline is implemented via script (because that's the only way to do it).  If any script is running, PowerShell assumes the engine is not idle, so no OnIdle events are raised.

PSReadline should raise OnIdle events while editing.

There are some interesting design choices in the area.
- We could support a configurable timeout for OnIdle processing.
- We could do OnIdle processing synchronously or asynchronously.
- If we do it synchronously, we could move the cursor past the command line so OnIdle output can't mess up the command line.
- If we do it asynchronously, we probably shouldn't return out of PSReadline while OnIdle is running or PowerShell might get confused, or worse, PSReadline might also get confused and multiple OnIdle event handlers could be running at the same time.

**Comment by kberridge** [comment]
Any idea when this will ship?  Waiting for Jump Location.

**Comment by lzybkr** [comment]
Soon I think - I've recently fixed the blocking issue I mentioned previously and there are probably enough bug fixes in now to justify a release.

**Comment by vors** [comment]
@kberridge meanwhile you can try [ZLocation](https://github.com/vors/ZLocation). It doesn't use OnIdle events, should just work with old versions of PSReadLine.
