### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException. Oops, something went wrong. Linked list insertion program. 

### ISSUE THREAD

**Issue by saloni2906** [lzybkr/PSReadLine#2914]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 127 Keys:
 c d Space " c : \ U s e r s \ R \ O n e D r i v e \ D e s k t o p \ c + + Space p r o g r a m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space L L _ i n s e r t i o n . c p p Space - o Space L L _ i n s e r t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L L _ i n s e r t i o n Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

[
![Screenshot (438)](https://user-images.githubusercontent.com/77798157/136689353-30d633a2-2dc5-40a8-ac4b-7c5f469b70a7.png)
](url)

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 166
BufferHeight: 32
```

### Steps to reproduce

#include <iostream>
#include <sstream>
#include <stdlib.h>
using namespace std;

struct node
{
    int data;
    struct node *next;
};

struct node *head = NULL;

//------------------------- functions declaration -----------------

void insert_begin();
void display();
void input_list();
void insert_last();
void insert_in_middle();
//---------------------------- main function ----------------
int main()
{
    cout<<"Type 1 to input element in the beginning "<<endl;
    cout<<"Type 2 to input element at last "<<endl;
    cout<<"Type 3 to input element in the middle "<<endl;
    int input;
    cin >> input;
    input_list();

    switch (input)
    {
    case 1:
        insert_begin();
        break;
    case 2:
        insert_last(); 
        break;   
    case 3:
        insert_in_middle(); 
        break;   
    }

    return 0;
}

//---------- --------------------- insert begin --------

void insert_begin()
{

    struct node *newp;
    newp = (struct node *)malloc(sizeof(struct node));
    cout << "\nEnter value to insert in the beginning \n";
    cin >> newp->data;
    newp->next = head;
    head = newp;
    display();
}

//------------------------------------- display -------------------------

void display()
{
    cout << "Linked list is: " << endl;
    struct node *ptr;
    ptr = head;
    while (ptr != NULL)
    {
        cout << ptr->data << " ";
        ptr = ptr->next;
    }
}

//----------------------------------- input_list -------------------------

void input_list()
{
    struct node *p;
    struct node *q;
    char ch;
    do
    //  while (ch != '0')
    {
        if (head == NULL)
        {
            p = (struct node *)malloc(sizeof(struct node));
            //   p->next= NULL;

            head = p;
        }
        else
        {
            q = (struct node *)malloc(sizeof(struct node));
            p->next = q;
            p = q;
            //  cout<<"enter value"<<endl;
            //  cin>>p->data;
        }
        cout << "enter value" << endl;
        cin >> p->data;
        p->next = NULL;
        cout << "press 0 to stop" << endl;
        cin >> ch;

    } while (ch != '0');
    display();
}

//------------------------------- insert at last ---------------------------

void insert_last(){
    struct node*p=head;
    //struct node*new_node;
   // p=head;
struct node*new_node= new struct node;   
          //dynamic memory allocation-- to get a memory block which new_node can point

cout << "Enter value to insert at the end \n";
    cin >> new_node->data;
    new_node->next=NULL;

    while(p->next!=NULL){    // loop to get p pointing at last element
        p=p->next;
    }
    p->next=new_node;
    display();
}

//------------------------------- insert in the middle ---------------------------

void insert_in_middle(){
    int info;
     struct node*p=head;
     struct node*new_node= new struct node; 
     cout << "Enter value to be inserted after which data \n";
     cin>>info;
     cout << "Enter value to insert after "<<info<<endl;
    cin >> new_node->data;
    new_node->next=NULL;

    while(p->data!=info)
    p=p->next;

    new_node->next=p->next;
    p->next=new_node;
    
    display();
}

### Expected behavior

PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_insert

### Actual behavior

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_in
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------   
Last 127 Keys:
 c d Space " c : \ U s e r s \ R \ O n e D r i v e \ D e s k t o p \ c + + Space p r o g r a m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space L L _ i n s e r t i o n . c p p Space - o Space L L _ i n s e r t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L L _ i n s e r t i o n Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------   
PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_ins
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------   
Last 127 Keys:
 c d Space " c : \ U s e r s \ R \ O n e D r i v e \ D e s k t o p \ c + + Space p r o g r a m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space L L _ i n s e r t i o n . c p p Space - o Space L L _ i n s e r t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L L _ i n s e r t i o n Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------   
PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_inse
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------   
Last 127 Keys:
 c d Space " c : \ U s e r s \ R \ O n e D r i v e \ D e s k t o p \ c + + Space p r o g r a m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space L L _ i n s e r t i o n . c p p Space - o Space L L _ i n s e r t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L L _ i n s e r t i o n Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------   
PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_inser
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------   
Last 127 Keys:
 c d Space " c : \ U s e r s \ R \ O n e D r i v e \ D e s k t o p \ c + + Space p r o g r a m s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space L L _ i n s e r t i o n . c p p Space - o Space L L _ i n s e r t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L L _ i n s e r t i o n Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo 
key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------   
PS C:\Users\R\OneDrive\Desktop\c++ programs> cd "c:\Users\R\OneDrive\Desktop\c++ programs\" ; if ($?) { g++ LL_insertion.cpp -o LL_insertion } ; if 
($?) { .\LL_insert
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
