### ISSUE TITLE
Exception : System.IO.IOException: The parameter is incorrect

### ISSUE THREAD

**Issue by shahrukhjaved786** [lzybkr/PSReadLine#2919]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 146 Keys:
 ` c d Space H : \ Enter
 l s Enter
 c d Space W Tab Tab Enter
 l s Enter
 c d Space t Tab Enter
 t o u c h Space f i l e 1 Enter
 UpArrow . t x t Enter
 m k Backspace Backspace Ctrl+l - - Backspace Backspace Backspace a ; o Backspace Backspace ; Backspace l i a s Space * h Backspace f i l e Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Space g r e p Space * f i e Backspace l e Enter
 l Backspace g e t 0 Backspace - h e l p Space * Backspace * Backspace g * s e r v i c e * Enter
 ` g e t - s e t Backspace r v i c e Enter
 UpArrow Enter
 Space Space Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![exception](https://user-images.githubusercontent.com/41357429/137184698-da957ad8-ad2b-4f54-8345-1270dbbc7cdf.png)
![last command before exception](https://user-images.githubusercontent.com/41357429/137184718-d19fd07b-8088-43c7-a4c8-856ca0235e12.png)

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 189
BufferHeight: 3000
```

### Steps to reproduce

> open PS in admin mode
> update help system
> run cmds like get-service , get-service *g*service* 2-3 times
> observe

### Expected behavior

System.IO.IOException: The parameter is incorrect.

### Actual behavior

no exception expected

**Comment by daxian-dbw** [comment]
@shahrukhJ Thank you for opening the issue and filling out the issue template so nicely. I really appreciate it!

This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
