### ISSUE TITLE
System.NullReferenceException on alt+h

### ISSUE THREAD

**Issue by mgpinf** [lzybkr/PSReadLine#2930]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
alt + h raises System.NullReferenceException
```

### Screenshot

Console state right before exception
![image](https://user-images.githubusercontent.com/56510798/138584615-d96493a0-4a2f-4632-8746-2442b13bb272.png)

### Environment data

```console
PS Version: 7.1.5
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta2
PSReadLine EditMode: Vi
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 208
BufferHeight: 48
```

### Steps to reproduce

Open powershell (latest-version cross-platform)
Enter the keybinding alt + h

### Expected behavior

Dynamic help for parameters like menu-complete

### Actual behavior

![image](https://user-images.githubusercontent.com/56510798/138584688-d7a8bc04-1911-4d62-81b0-0398bfb8760b.png)

**Comment by daxian-dbw** [comment]
This was fixed by #2292, and the fix is included in the [2.2.0-beta3 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.2.0-beta3).
