### ISSUE TITLE
Way to bind two function to one key.

### ISSUE THREAD

**Issue by roachsinai** [lzybkr/PSReadLine#2931]
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

I wanna map Ctrl+SpaceBar to function AcceptLine following function ForwardChar, then I can use it to run the lastest command directly which mached the current inputs.

What I do now:

Set-PSReadLineKeyHandler -Key Ctrl+Spacebar -Function ForwardChar,AcceptLine

But got error that not support. Is there a way to make it? Thanks in advanced!

**Comment by daxian-dbw** [comment]
You can register a script block with the key binding and do what you intend in the script block. Check https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/SamplePSReadLineProfile.ps1 for some examples.
