### ISSUE TITLE
gpresult without parameter and   Ctrl+l

### ISSUE THREAD

**Issue by N3rDM0nK3y** [lzybkr/PSReadLine#2933]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oups, un problème s'est produit. Signalez ce bogue avec les détails ci-dessous.
Signaler sur GitHub : https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Dernières 10 touches :
 g p r e s u l t Enter
 Ctrl+l

Exception :
System.IO.IOException: Paramètre incorrect.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.Console.SetWindowPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![bug powershell](https://user-images.githubusercontent.com/93287892/139136769-13e39856-9b97-42ed-bad9-75bdc441cb03.PNG)

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 192
BufferHeight: 3000
```

### Steps to reproduce

1- open powershell
2- Type: gpresult + enter
3- Clear screen with shortcut: Ctrl+l

### Expected behavior

Clear screen

### Actual behavior

Parameter execption

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
