### ISSUE TITLE
Try to compile and run, but error

### ISSUE THREAD

**Issue by DavidUKr** [lzybkr/PSReadLine#2938]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Last 200 Keys:
 t y \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space t e m p C o d e R u n n e r F i l e . c Space - o Space t e m p C o d e R u n n e r F i l e Space } Space ; Space i f Space ( $ ? ) Space { Space . \ t e m p C o d e R u n n e r F i l e Space } Enter
 c l e a r Enter
 c d Space " d : \ C o d i n g \ U n i v e r s i t y \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space L a b 2 - p b 6 . c Space - o Space L a b 2 - p b 6 Space } Space ; Space i f Space ( $ ? ) Space { Space . \ L a b 2 - p b 6 Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -5.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

PS D:\Coding\University> cd "d:\Coding\University\" ; if ($?) { gcc Lab2-pbcd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> cd "d:\Coding\University\" ; if ($?) { gcc tempCodeRunnerFile.c -o tempCodeRunnerFile } ; if ($?) { .\tempCodeRunnerFile }
>> clear
>> cd "d:\Coding\University\" ; if ($?) { gcc Lab2-pb6.c -o Lab2-pb6 } ; if ($?) { .\Lab2-pb6 }
Oops, something went wrong.  Please report this bug with the details below.

### Environment data

```console
$hostName = $Host.Name
>>     if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
>>         $id = $PID; $inWindowsTerminal = $false
>>         while ($true) {
>>             $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
>>             if (!$p -or !$p.Name) { break }
>>             if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
>>             $id = $p.ParentProcessId
>>         }
>>         if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
>>     }
>>
>>     $m = Get-Module PSReadline
>>     $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
>>     if ($pre) { $v = "$v-$pre" }
>>     $os = if ($IsLinux -or $IsMacOS) { uname -a } else { (dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion }
>>
>>     Write-Host ''
>>     Write-Host "PS Version: $($PSVersionTable.PSVersion)"
>>     Write-Host "PS HostName: $hostName"
>>     Write-Host "PSReadLine Version: $v"
>>     Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMode)"
>>     Write-Host "OS: $os"
>>     Write-Host "BufferWidth: $([console]::BufferWidth)"
>>     Write-Host "BufferHeight: $([console]::BufferHeight)"
>>     Write-Host ''
```

### Steps to reproduce

#include <stdio.h>
#include <math.h>

int myround(double n){
    int i;
    i=n*10;
    if(i%10>=5){
        n=ceil(n);
    }
    else {
        n=floor(n);
    }
    return n;
    printf("\n");
}

int main(){

myround(3.75);
myround(3.2);
myround(3);
myround(3.0);
myround(3.89);
myround(3.5;
myround(3.50);
return 0;
}

### Expected behavior

Compile, giving errors and warnings or running the program

### Actual behavior

"Oops, something went wrong." message an then the following.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
