### ISSUE TITLE
ShowParameterHelp does not clear multiline parameter help on escape

### ISSUE THREAD

**Issue by kborowinski** [lzybkr/PSReadLine#3356]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![Animation](https://user-images.githubusercontent.com/16168755/175496040-8e5ddcba-9546-4ebb-aa59-f0557ff9d321.gif)

### Environment data

```console
PS Version: 7.3.0-preview.3
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 141
BufferHeight: 36
```

### Steps to reproduce

Press `Alt+H` on  parameter with multiline help and then `Esc` or `Alt+H` again.

### Expected behavior

Multiline parameter help is cleared on escape.

### Actual behavior

Part of parameter help is not cleared.

**Comment by daxian-dbw** [comment]
@kborowinski what is the module name for the `Show-KBComputerReport` command? I need that to reproduce the issue locally.

**Comment by kborowinski** [comment]
@daxian-dbw I have prepared short test case. It has the same outcome. Paste following code and try to invoke parameter help on `Server` property:
```powershell
function Get-Report {
<#
	.SYNOPSIS
	Display status of the domain joined computers.
	.DESCRIPTION
	The Get-Report cmdlet displays status of specified computer, group of computers or all computers in the domain.
	You can specify additional parameters to fine-tune the query.
	.PARAMETER Server
	Specifies Windows Server type.
	Possible values for this parameter include:
	Any     - any Windows Server type
	W2K3    - Windows Server 2003/R2
	W2K8    - Windows Server 2008
	W2K8R2  - Windows Server 2008 R2
	W2K12   - Windows Server 2012
	W2K12R2 - Windows Server 2012 R2
	W2K16   - Windows Server 2016
	W2K19   - Windows Server 2019
	W2K22   - Windows Server 2022
#>
	[CmdletBinding()]
	param (
		[String]$Server
	)
}
```
Visuals:
![Animation](https://user-images.githubusercontent.com/16168755/175655995-c7671dfb-9544-49b3-9177-9295c42df1fa.gif)

**Comment by daxian-dbw** [comment]
@kborowinski Thanks, that helps!
