### ISSUE TITLE
CompletionResult tooltips aren't displayed when tooltip text == ListItem/CompletionText

### ISSUE THREAD

**Issue by thegraffix** [lzybkr/PSReadLine#3903]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

ISE doesn't filter out tooltips when the tooltip text is the same as the ListItem/CompletionText, but PSReadLine [does](https://github.com/PowerShell/PSReadLine/blob/e57f7d691d8df8c1121fddf47084f96aea74a688/PSReadLine/Completion.cs#L547C36-L547C36).

Explorer:
![image](https://github.com/PowerShell/PSReadLine/assets/57874058/5721298e-75c9-43dc-9b09-9f401a6390b2)

Console:
![Console](https://github.com/PowerShell/PSReadLine/assets/57874058/9653b6a3-3bea-4a12-b0d0-138703baeb22)

ISE:
![ISE](https://github.com/PowerShell/PSReadLine/assets/57874058/2c3a7781-d083-443d-867f-5458deb1186d)

### Environment data

```console
PS Version: 5.1.19041.3803
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 170
BufferHeight: 3000
```

### Steps to reproduce

This is the test function I used:

```
function Test-ToolTip
{
    [CmdletBinding()]
    param (
        [ArgumentCompleter({
            param ($CommandName, $ParameterName, $WordToComplete, $CommandAst, $FakeBoundParameters)
            Get-ChildItem -Path 'C:\Test' -File | Where-Object {$_.Name -like "*$WordToComplete*"} | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        })]
        [string]$FileName
    )

    Write-Output $FileName
}
```

### Expected behavior

Tooltips are displayed even when the tooltip text is the same as the ListItem/CompletionText.

### Actual behavior

Tooltips are not displayed when the tooltip text is the same as the ListItem/CompletionText.

**Comment by daxian-dbw** [comment]
This is by design. PSReadLine chooses to not render the tooltips if it doesn't provide additional information.
