### ISSUE TITLE
History should automatically persist across sessions

### ISSUE THREAD

**Issue by jhclark** [lzybkr/PSReadLine#57]
This is something that I believe 0.x did that is no longer in 1.x. PowerShell natively doesn't do this and it would be awesome in a new session to instantly have the up arrow recover the last command from the previous session.

Was there something technical standing in the way of putting this in 1.x? Or might this make a come back at some point?
# Enhancement

**Comment by cydhaselton** [comment]
Are there requirements to configuring up arrow to access previously added history? I'm adding history pre-import of psreadline but using the up arrow does nothing
