### ISSUE TITLE
BACKSPACE changed from PSReadLine 2.0.0-beta1

### ISSUE THREAD

**Issue by chuanjiao10** [lzybkr/PSReadLine#619]
I found BACKSPSCE changed from PSReadLine 2.0.0-beta1
from  BACKSPSCE  (ctrl+H)    to  ascii127(ctrl + ?)

Steps to reproduce
------------------
Install-Module PSReadLine -AllowPrerelease -Force -AllowClobber 
exit
pwsh
press BACKSPSCE

I changed BACKSPSCE setting in termal, then PowerShell is working fine.

Environment data
----------------
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      6.0.0                                                                                                             
PSEdition                      Core                                                                                                              
GitCommitId                    v6.0.0                                                                                                            
OS                             Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018                                               
Platform                       Unix                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           
WSManStackVersion              3.0    

(get-module PSReadLine).version
Major  Minor  Build  Revision
2      0      0      -1

**Comment by daxian-dbw** [comment]
I don't understand this issue. The repro steps don't show anything either.
@chuanjiao10 can you elaborate on the issue and give more detailed repro steps?

**Comment by chuanjiao10** [comment]
![backspace-xshell](https://user-images.githubusercontent.com/8968667/38162284-e7c13b46-3510-11e8-9c28-e9436ad18e3e.png)

**Comment by chuanjiao10** [comment]
I checked the latest version of putty, v 0.70 .
I found putty's default BACKSPSCE set to ascii127 (ctrl + ?), so putty users do not feel the key change.
