### ISSUE TITLE
The last line of the partial string appears in the cursor line

### ISSUE THREAD

**Issue by chuanjiao10** [lzybkr/PSReadLine#669]
When paste command:
 If last line strings long than cursor line,
 At the first line of the pasted command end,shows the last line of the partial string. 

Note:
 This only shows an error.The first line of the pasted command works fine.

Steps to reproduce
------------------
```powershell
$本机线程池中最大线程数 = $null
$本机线程池中最大异步io线程数 = $null
[System.Threading.ThreadPool]::GetMaxThreads([ref]$本机线程池中最大线程数,[ref]$本机线程池中最大异步io线程数) 
write-host "本机线程池中最大线程数  $本机线程池中最大线程数"
```

retrun
------------------

![psreadline_huan_chong_qu](https://user-images.githubusercontent.com/8968667/38775545-f786c44e-40b7-11e8-8f9a-570af1daa8ef.jpg)

Environment data
----------------

[aaaa@cent74 ~]$ echo $LANG
en_us.UTF-8
[aaaa@cent74 ~]$ pwsh
PowerShell v6.1.0-preview.1

Set-PSReadlineOption -EditMode Windows

(Get-Module PSReadline).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      0      -1

**Comment by SteveL-MSFT** [comment]
This doesn't repro for me.  Need more clear instructions.  I even set the terminal window to have less width than the text.

**Comment by chuanjiao10** [comment]
thanks for reply,I did not find this problem on powershell 6.1 version, if all hands don't mind, I will close this issue 3 days later.
