### ISSUE TITLE
'GetMenuItem' throw ArgumentOutOfRangeException for CKJ completion items

### ISSUE THREAD

**Issue by kmyzr** [lzybkr/PSReadLine#847]
問題が発生しました。このバグを以下の詳細と共に報告してください。
GitHub で報告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
直前 200 個のキー:
 s t o p - p r o Ctrl+Space Space - n a e m Space Backspace Backspace Backspace m e Space e x c e l Enter
 $ a Backspace A p p Space = Space Space n e w - o b j e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace $ A p p Space = Space N e w - o b j e c t Ctrl+Space Ctrl+Space Space - c o m Ctrl+Space Space E x c e l . A p p l i c a t i o n Enter
 Backspace Backspace Backspace Backspace $ A p p . V i s i b l e Space = Space $ F a l s e Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace T r u e Enter
 $ A p p . W o r k b o o k s . O p e n 　 Space Backspace Space Space = Space Backspace Backspace Backspace Backspace ( " D : \ LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow Ctrl+Space u Enter
 Ctrl+Space RightArrow Enter
 Ctrl+Space

例外:
System.ArgumentOutOfRangeException: インデックスおよび長さは文字列内の場所を参照しなければなりません。
パラメーター名:length
   場所 System.String.Substring(Int32 startIndex, Int32 length)
   場所 Microsoft.PowerShell.PSConsoleReadLine.GetMenuItem(String item, Int32 columnWidth)
   場所 Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   場所 Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   場所 Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by xa0082249956** [comment]
Same issue here.

## Possible Reason

The CJK Character takes more space than English letter.

## Step to Reproduce

```PowerShell
New-Item 啊啊啊啊啊啊啊啊啊啊啊啊.txt
New-Item 啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊.txt
```

Now type `ls`, press `Enter` and then `Ctrl`+`Space`. And you can see the exception.

## Exception Content

### Environment                                                                                                                                                                                        PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.1
OS: Microsoft Windows 10.0.18945
Last 200 Keys
```
 Spacebar 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 . x l s x Spacebar 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 . x l s x Backspace Backspace Backspace Backspace Backspace . x t Backspace Backspace Backspace . t x t Enter
 m v Spacebar 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 . x l s x Backspace x Spacebar 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 啊 . x l s x Backspace Backspace Backspace t x Backspace Backspace Backspace t x t Enter
 l s Enter
 l s Spacebar Ctrl+@ Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace G e t - F Backspace Backspace Backspace Backspace Backspace Backspace M e n u C o m p l e t e Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 Ctrl+@ Ctrl+@ Ctrl+@ l s Backspace Backspace Spacebar Ctrl+@ Backspace Backspace l s Spacebar Ctrl+@
```

### Exception
```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.GetMenuItem(String item, Int32 columnWidth)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by SteveL-MSFT** [comment]
Ok, I understand the issue.  PSReadLine is calculating the number of buffer cells correctly (2 cells per char), but then tried to simply do a SubString() call with that value which is incorrect since SubString() works in chars and not cells.  Working on a fix.
